"""Acorn color themes — semantic tokens + Textual CSS colors."""

THEMES = {
    'dark': {
        'name': 'dark',
        'icon': '🌰',
        # Soft dark — charcoal, not black
        'bg': '#1e2030',
        'bg_header': '#262840',
        'bg_input': '#262840',
        'bg_panel': '#262840',
        'fg': '#cdd6f4',
        'border': '#45475a',
        # Accents — soft blue/lavender
        'accent': '#89b4fa',
        'accent2': '#cba6f7',
        'success': '#a6e3a1',
        'error': 'bold #f38ba8',
        'warning': '#f9e2af',
        'info': 'dim',
        'muted': '#6c7086',
        # Tools
        'tool_icon': '#f9e2af',
        'tool_done': '#a6e3a1',
        'read_icon': '#89b4fa',
        'edit_icon': '#f9e2af',
        'diff_add': '#a6e3a1',
        'diff_del': '#f38ba8',
        # Text
        'thinking': 'italic #89b4fa',
        'usage': '#6c7086',
        'prompt_user': '#89b4fa',
        'prompt_project': '#a6e3a1',
        'prompt_branch': '#f9e2af',
        'prompt_symbol': 'bold #89b4fa',
        # Bars
        'plan_bar_bg': '#cdd6f4 on #3b3d6b',
        'exec_bar_bg': '#cdd6f4 on #2b4a3a',
        'plan_label': 'bold white on #5b5dab',
        'exec_label': 'bold white on #3b7a5a',
        # Other
        'banner': 'bold #cdd6f4',
        'banner_sub': '#6c7086',
        'code_theme': 'monokai',
        'separator': '#45475a',
    },
    'oled': {
        'name': 'oled',
        'icon': '⬛',
        # Pure black and white — OLED battery saver
        'bg': '#000000',
        'bg_header': '#0a0a0a',
        'bg_input': '#0a0a0a',
        'bg_panel': '#0a0a0a',
        'fg': '#e0e0e0',
        'border': '#333333',
        # Monochrome accents
        'accent': '#ffffff',
        'accent2': '#bbbbbb',
        'success': '#ffffff',
        'error': 'bold #ff4444',
        'warning': '#cccccc',
        'info': 'dim',
        'muted': '#666666',
        # Tools
        'tool_icon': '#cccccc',
        'tool_done': '#ffffff',
        'read_icon': '#aaaaaa',
        'edit_icon': '#cccccc',
        'diff_add': '#ffffff',
        'diff_del': '#ff4444',
        # Text
        'thinking': 'italic #888888',
        'usage': '#555555',
        'prompt_user': '#ffffff',
        'prompt_project': '#cccccc',
        'prompt_branch': '#aaaaaa',
        'prompt_symbol': 'bold #ffffff',
        # Bars
        'plan_bar_bg': '#000000 on #333333',
        'exec_bar_bg': '#000000 on #222222',
        'plan_label': 'bold #000000 on #ffffff',
        'exec_label': 'bold #000000 on #cccccc',
        # Other
        'banner': 'bold #ffffff',
        'banner_sub': '#555555',
        'code_theme': 'monokai',
        'separator': '#333333',
    },
    'light': {
        'name': 'light',
        'icon': '☀️',
        'bg': '#fafafa',
        'bg_header': '#f0f0f0',
        'bg_input': '#f0f0f0',
        'bg_panel': '#f0f0f0',
        'fg': '#1a1a2e',
        'border': '#d4d4d8',
        'accent': '#2563eb',
        'accent2': '#7c3aed',
        'success': '#16a34a',
        'error': 'bold #dc2626',
        'warning': '#ca8a04',
        'info': 'dim',
        'muted': '#71717a',
        'tool_icon': '#ca8a04',
        'tool_done': '#16a34a',
        'read_icon': '#2563eb',
        'edit_icon': '#ca8a04',
        'diff_add': '#16a34a',
        'diff_del': '#dc2626',
        'thinking': 'italic #2563eb',
        'usage': '#71717a',
        'prompt_user': '#2563eb',
        'prompt_project': '#16a34a',
        'prompt_branch': '#ca8a04',
        'prompt_symbol': 'bold #2563eb',
        'plan_bar_bg': '#1a1a2e on #dbeafe',
        'exec_bar_bg': '#1a1a2e on #dcfce7',
        'plan_label': 'bold white on #2563eb',
        'exec_label': 'bold white on #16a34a',
        'banner': 'bold #1a1a2e',
        'banner_sub': '#71717a',
        'code_theme': 'friendly',
        'separator': '#d4d4d8',
    },
    'oak': {
        'name': 'oak',
        'icon': '🪵',
        # Warm earthy — terracotta, sand, dried clay
        'bg': '#2c2016',
        'bg_header': '#382a1e',
        'bg_input': '#382a1e',
        'bg_panel': '#382a1e',
        'fg': '#e8d5b7',
        'border': '#6b5240',
        # Earthy accents — terracotta, sage, sand
        'accent': '#e09060',
        'accent2': '#b8a080',
        'success': '#a3b87a',
        'error': 'bold #d47070',
        'warning': '#d4a84a',
        'info': 'dim',
        'muted': '#8a7560',
        # Tools
        'tool_icon': '#d4a84a',
        'tool_done': '#a3b87a',
        'read_icon': '#c09868',
        'edit_icon': '#d4a84a',
        'diff_add': '#a3b87a',
        'diff_del': '#d47070',
        # Text
        'thinking': 'italic #e09060',
        'usage': '#8a7560',
        'prompt_user': '#e09060',
        'prompt_project': '#a3b87a',
        'prompt_branch': '#d4a84a',
        'prompt_symbol': 'bold #e09060',
        # Bars — warm tones
        'plan_bar_bg': '#e8d5b7 on #4a3828',
        'exec_bar_bg': '#e8d5b7 on #3a4a28',
        'plan_label': 'bold #2c2016 on #e09060',
        'exec_label': 'bold #2c2016 on #a3b87a',
        # Other
        'banner': 'bold #e09060',
        'banner_sub': '#8a7560',
        'code_theme': 'monokai',
        'separator': '#6b5240',
    },
    'forest': {
        'name': 'forest',
        'icon': '🌲',
        # Deep green — pine, moss, fern
        'bg': '#0c1f14',
        'bg_header': '#12301e',
        'bg_input': '#12301e',
        'bg_panel': '#12301e',
        'fg': '#b0d8b0',
        'border': '#2a5a3a',
        # Green accents — emerald, moss, fern
        'accent': '#50c878',
        'accent2': '#78b090',
        'success': '#70e890',
        'error': 'bold #e87070',
        'warning': '#e8d060',
        'info': 'dim',
        'muted': '#4a7a5a',
        # Tools
        'tool_icon': '#e8d060',
        'tool_done': '#70e890',
        'read_icon': '#50c878',
        'edit_icon': '#e8d060',
        'diff_add': '#70e890',
        'diff_del': '#e87070',
        # Text
        'thinking': 'italic #50c878',
        'usage': '#4a7a5a',
        'prompt_user': '#70e890',
        'prompt_project': '#50c878',
        'prompt_branch': '#e8d060',
        'prompt_symbol': 'bold #70e890',
        # Bars — deep green tones
        'plan_bar_bg': '#b0d8b0 on #1a4028',
        'exec_bar_bg': '#b0d8b0 on #285018',
        'plan_label': 'bold #0c1f14 on #50c878',
        'exec_label': 'bold #0c1f14 on #70e890',
        # Other
        'banner': 'bold #50c878',
        'banner_sub': '#4a7a5a',
        'code_theme': 'monokai',
        'separator': '#2a5a3a',
    },
}

DEFAULT_THEME = 'dark'


def get_theme(name: str) -> dict:
    return THEMES.get(name, THEMES[DEFAULT_THEME])


def list_themes() -> list:
    return list(THEMES.keys())
